### ISSUE TITLE
cannot distribute in 0-1 range? (contrary to fast implementation)

### ISSUE THREAD

**Issue by juliendorra** [kchapelier/poisson-disk-sampling#12]
Hi, thanks for this really nice lib!

I just tested both this implementation and the fast-2d-poisson-disk-sampling implementation.

With the fast implementation, I can generate normalized positions values in the 0-1 range, but cannot with this implementation: using `fill()` only returns 1 point, trying to use `next()` returns null

code used: 
```
var pds = new PoissonDiskSampling({
    shape: [1, 1],
    minDistance: 0.05,
    tries: 10,
});
```

I want to use a distanceFunction, so my workaround will be to use `shape: [10, 10]` and divide everything back, but it's not elegant and might lead to errors.

Do you see a reason why it fails?

**Comment by kchapelier** [comment]
Hello, thanks for your feedback.

That's not the intended behaviour, it should indeed be able to generate points in the provided shape. I'll be looking into this issue this week-end.

**Comment by kchapelier** [comment]
The intended behaviour is that `fill()` should return an array with all the points (more than one in this case), additional calls to `next()` will still return `null`.

**Comment by kchapelier** [comment]
I think the issue is that the builds in the repository are slightly outdated. @juliendorra Can you confirm if you're using one of the compiled build from this repository, not the NPM package.

This issue was fixed 2 weeks _after_ the generation of the last build ( https://github.com/kchapelier/poisson-disk-sampling/commit/e85d0a753b3c4304f6ebd0829878481024042c44 ). I'll fix this this week-end.

**Comment by juliendorra** [comment]
Hi! Thanks a lot for the super quick reply 😃🙏👍🚀

I'm using the min.js from the CDN URL on the readme (wanted to test it quick! 😅😄)
