### ISSUE TITLE
Minimum distance is not respected for points added manually.

### ISSUE THREAD

**Issue by JacobValore** [kchapelier/poisson-disk-sampling#13]
Example code that frequently shows the behavior:
```
var pds1D = new PoissonDiskSampling({
	shape: [300],
	minDistance: 30,
	maxDistance: 50,
	tries: 10
});
pds1D.addPoint([0]);
pds1D.addPoint([300]);
console.log(pds1D.fill());
```
And a sample output from this: (rounded)
`[ 0,  300,  34.983,  252.519,  78.478,  299.370,  214.373,  122.566,  178.245 ]`
Clearly, point 5 (299.370) is not respecting the minDistance from point 1 (300). From my testing, it does seem to respect the distance to point 0.

**Comment by kchapelier** [comment]
Thanks for reporting the issue. It puzzled me for a while. This happens when one of the coordinate of the point is exactly equal to the outer bound of the shape for this axis. In this case, ```pds1D.addPoint([299.999]);``` would not trigger the issue for example, and ```pds1D.addPoint([300.001]);``` would be outright rejected as out-of-bound.

When such a point is generated using the ```.fill()``` method, it is rejected, but the current implementation of the `.addPoint()` method considers it as valid. I'll probably fix the `.addPoint()` method by making sure those points are rejected as out-of-bound and update the doc to be more precise about all this. Probably doing this in the coming days.

**Comment by kchapelier** [comment]
This is fixed on the repo and will shortly be pushed to npm under as 2.3.0
