### ISSUE TITLE
Add maxPoints value to constructor or fill()

### ISSUE THREAD

**Issue by JacobValore** [kchapelier/poisson-disk-sampling#14]
This would be a nice enhancement, to be able to limit the maximum number of points that can be placed. It could go in the constructor or as a value for fill (as in fill(30) to fill in a max of 30 points).

It could be a nice alternative to a for loop calling pds.next() 30 times.

**Comment by kchapelier** [comment]
I think this might be confusing for the end user who might not really understand how the underlying Bridson algorithm works. They might expect the points to be plotted uniformly in the space, but would instead end up with a single clump of points in an otherwise completely empty space (which would be counter intuitive for a "fill" method).

An alternative would be to add a "iterate(x)" method, but honestly at this point I'd rather avoid making changes to the public API. The .next() method makes it possible to implement this (and much more, i.e. streaming api, iterator, ...) fairly easily.
